//
//  HomeModels.swift
//  FlickrImageGallery
//
//  Created by Gabriel Targon on 29/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
    enum ImagesArray {
        struct Request {}
        
        struct Response {
            let images: [FlickrImage]
        }
        
        struct ViewModel {
            let images: [FlickrImage]
        }
    }
    
    enum Image {
        struct Request {
            let imageURL: String
        }
        
        struct Response {
            let imageURL: UIImage
        }
        
        struct ViewModel {
            
        }
    }
}
