//
//  HomePresenter.swift
//  FlickrImageGallery
//
//  Created by Gabriel Targon on 29/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentImagesArray(response: Home.ImagesArray.Response)
    func presentServiceError()
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Present Images
    func presentImagesArray(response: Home.ImagesArray.Response) {
        let viewModel = Home.ImagesArray.ViewModel(images: response.images)
        viewController?.displayImages(viewModel: viewModel)
    }
    
    func presentServiceError() {
        viewController?.displayServiceErrorAlert()
    }
}
