//
//  HomeWorkerTests.swift
//  FlickrImageGallery
//
//  Created by Gabriel Targon on 03/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import FlickrImageGallery

class HomeWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: HomeWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        sut = HomeWorker()
    }
     
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Tests
    
    func testGetFlickrImages() {
        var promisseResult: Result<Home.ImagesArray.Response, ServiceError>?
        
        sut.getFlickrImages { (result) in
            promisseResult = result
        }
        
//        XCTAssertNotNil(promisseResult)
        switch promisseResult {
        case .success(let result):
            XCTAssertNotNil(result)
        case .failure:
            break
        case .none:
            break
        }
    }
}
