//
//  HomeViewControllerTests.swift
//  FlickrImageGallery
//
//  Created by Gabriel Targon on 03/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FlickrImageGallery
import XCTest

class HomeViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: HomeViewController!
    var window: UIWindow!
    var interactorSpy: HomeInteractorSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow(frame: UIScreen.main.bounds)
        interactorSpy = HomeInteractorSpy()
        setupHomeViewController()
    }
    
    override func tearDown() {
        window = nil
        sut = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupHomeViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Home", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
        _ = sut.view
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testDisplayImages() {
        sut.displayImages(viewModel: Home.ImagesArray.ViewModel(images: HomeSeeds.imagesArray))
        XCTAssertNotEqual(sut.cellData.count, 0)
    }
    
    func testDisplayServiceErrorAlert() {
        loadView()
        sut.displayServiceErrorAlert()
        XCTAssertNotEqual(window.rootViewController, sut)
    }
    
    func testCollectionView() {
        sut.displayImages(viewModel: Home.ImagesArray.ViewModel(images: HomeSeeds.imagesArray))
        let index = IndexPath(row: 0, section: 0)
        sut.collectionView(sut.collectionView, cellForItemAt: index)
        XCTAssertNotEqual(sut.cellData.count, 0)
    }
    
}
