//
//  HomePresenterTests.swift
//  FlickrImageGallery
//
//  Created by Gabriel Targon on 03/12/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FlickrImageGallery
import XCTest

class HomePresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: HomePresenter!
    var viewControllerSpy: HomeViewControllerSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        sut = HomePresenter()
        viewControllerSpy = HomeViewControllerSpy()
        sut.viewController = viewControllerSpy
    }
    
    override func tearDown() {
        sut = nil
        viewControllerSpy = nil
        super.tearDown()
    }
    
    // MARK: Tests
    
    func testPresentImagesArray() {
        sut.presentImagesArray(response: Home.ImagesArray.Response(images: HomeSeeds.imagesArray))
        XCTAssertTrue(viewControllerSpy.displayImagesCalled)
    }
    
    func testPresentServiceError() {
        sut.presentServiceError()
        XCTAssertTrue(viewControllerSpy.displayServiceErrorAlertCalled)
    }
    
}
